#!/bin/bash

g++ -I../include ..//sql/gen_lex_hash.cc -o sql/gen_lex_hash
cp sql/gen_lex_hash ../sql/

gcc ../scripts/comp_sql.c -o scripts/comp_sql
cp ../build-x86_64/extra/comp_err ../extra

if [ "${1}" == "${NARCH}" ];then
  make ${MAKE_J} -C extra comp_err
fi;
